name: Run Form Automation

on:
  schedule:
    # Every day at 5 AM UTC from November to December (9 PM PST)
    - cron: '0 5 * 11-12 *'
    # Every day at 5 AM UTC from January to March (9 PM PST)
    - cron: '0 5 * 1-3 *'
    # Every day at 4 AM UTC from March to October (9 PM PDT)
    - cron: '0 4 * 3-10 *'
  workflow_dispatch:
  
jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | cut -d ' ' -f 3 | cut -d '.' -f 1)
          wget https://chromedriver.storage.googleapis.com/$CHROME_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver
      - name: Run the script
        env:
          TOKEN: ${{ secrets.TOKEN }}
          EMAIL: ${{ secrets.EMAIL }}
          TEL: ${{ secrets.TEL }}
        run: |
          python parking_registration.py
