name: Run Form Automation

on:
  schedule:
    # Every day at 5 AM UTC from November to December (9 PM PST)
    - cron: '0 5 * 11-12 *'
    # Every day at 5 AM UTC from January to March (9 PM PST)
    - cron: '0 5 * 1-3 *'
    # Every day at 4 AM UTC from March to October (9 PM PDT)
    - cron: '0 4 * 3-10 *'
  workflow_dispatch:
  
jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
      - name: Install ChromeDriver
        run: |
          page_content=$(curl -s https://googlechromelabs.github.io/chrome-for-testing/)
          chromedriver_url=$(echo "$page_content" | grep -oE 'https://storage.googleapis.com/chrome-for-testing-public/[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/linux64/chromedriver-linux64.zip' | head -1)
          wget -O chromedriver_linux64.zip $chromedriver_url
          unzip chromedriver_linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver
      - name: Run the script
        env:
          TOKEN: ${{ secrets.TOKEN }}
          EMAIL: ${{ secrets.EMAIL }}
          TEL: ${{ secrets.TEL }}
        run: |
          Xvfb :99 -ac &
          export DISPLAY=:99
          python parking_registration.py
      - name: List files
        run: ls -la
      - name: Upload ChromeDriver log
        uses: actions/upload-artifact@v2
        with:
          name: chromedriver-log
          path: chromedriver.log
